// Curated list of app routes/functions for the Super Admin chat "/" mention.
export type AppPage = { path: string; label: string; group: string; description?: string };

export const APP_PAGES: AppPage[] = [
  { path: "/Dashboard", label: "Dashboard", group: "Core", description: "Store dashboard overview" },
  { path: "/orders", label: "Orders", group: "Sales" },
  { path: "/orders/import", label: "Orders Import", group: "Sales" },
  { path: "/customers", label: "Customers", group: "Sales" },
  { path: "/inventory/products", label: "Products", group: "Inventory" },
  { path: "/inventory/stock-record", label: "Stock Record", group: "Inventory" },
  { path: "/inventory/buy-stock", label: "Buy Stock", group: "Inventory" },
  { path: "/inventory/agent-stock", label: "Agent Stock", group: "Inventory" },
  { path: "/inventory/faulty", label: "Faulty Stock", group: "Inventory" },
  { path: "/inventory/waybill", label: "Waybill", group: "Inventory" },
  { path: "/purchase-orders", label: "Purchase Orders", group: "Inventory" },
  { path: "/suppliers", label: "Suppliers", group: "Inventory" },
  { path: "/staff", label: "Staff", group: "People" },
  { path: "/attendance", label: "Attendance", group: "People" },
  { path: "/payroll", label: "Payroll", group: "People" },
  { path: "/agents", label: "Agents", group: "People" },
  { path: "/finance", label: "Finance", group: "Finance" },
  { path: "/finance/commissions", label: "Commissions", group: "Finance" },
  { path: "/finance/refunds", label: "Refunds", group: "Finance" },
  { path: "/wallet", label: "Wallet", group: "Finance" },
  { path: "/billing", label: "Billing", group: "Finance" },
  { path: "/marketing/sales-forms", label: "Sales Forms", group: "Marketing" },
  { path: "/marketing/templates", label: "Message Templates", group: "Marketing" },
  { path: "/integrations", label: "Integrations", group: "Setup" },
  { path: "/webhooks", label: "Webhooks", group: "Setup" },
  { path: "/Settings", label: "Settings", group: "Setup" },
  { path: "/chat", label: "Team Chat", group: "Communication" },
  { path: "/customer-service", label: "Customer Service", group: "Communication" },
  { path: "/tasks", label: "Tasks", group: "Productivity" },
  { path: "/productivity", label: "Productivity", group: "Productivity" },
  { path: "/reports/daily", label: "Daily Reports", group: "Reports" },
  { path: "/reports/activity", label: "Activity Reports", group: "Reports" },
  { path: "/reports/export", label: "Export Reports", group: "Reports" },
  { path: "/admin", label: "Super Admin Overview", group: "Admin" },
  { path: "/admin/tenants", label: "Tenants", group: "Admin" },
  { path: "/admin/subscriptions", label: "Subscriptions", group: "Admin" },
  { path: "/admin/flags", label: "Feature Flags", group: "Admin" },
  { path: "/admin/broadcasts", label: "Broadcasts", group: "Admin" },
  { path: "/admin/audit", label: "Audit Log", group: "Admin" },
  { path: "/admin/system-health", label: "System Health", group: "Admin" },
  { path: "/admin/integrations", label: "Integrations Admin", group: "Admin" },
];
