/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ProductivityRouteImport } from './routes/productivity'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CustomerServiceRouteImport } from './routes/customer-service'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as StoreManagementRouteImport } from './routes/StoreManagement'
import { Route as SettingsRouteImport } from './routes/Settings'
import { Route as DashboardRouteImport } from './routes/Dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoreProductsRouteImport } from './routes/store.products'
import { Route as StoreOrdersRouteImport } from './routes/store.orders'
import { Route as ReportsExportRouteImport } from './routes/reports.export'
import { Route as ReportsActivityRouteImport } from './routes/reports.activity'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OrderFormIdRouteImport } from './routes/order.$formId'
import { Route as MarketingSalesFormsRouteImport } from './routes/marketing.sales-forms'
import { Route as InventoryWaybillRouteImport } from './routes/inventory.waybill'
import { Route as InventoryStockRecordRouteImport } from './routes/inventory.stock-record'
import { Route as InventoryProductsRouteImport } from './routes/inventory.products'
import { Route as InventoryFaultyRouteImport } from './routes/inventory.faulty'
import { Route as InventoryBuyStockRouteImport } from './routes/inventory.buy-stock'
import { Route as InventoryAgentStockRouteImport } from './routes/inventory.agent-stock'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminFlagsRouteImport } from './routes/admin.flags'
import { Route as AdminBroadcastsRouteImport } from './routes/admin.broadcasts'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductivityRoute = ProductivityRouteImport.update({
  id: '/productivity',
  path: '/productivity',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerServiceRoute = CustomerServiceRouteImport.update({
  id: '/customer-service',
  path: '/customer-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreManagementRoute = StoreManagementRouteImport.update({
  id: '/StoreManagement',
  path: '/StoreManagement',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/Settings',
  path: '/Settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreProductsRoute = StoreProductsRouteImport.update({
  id: '/store/products',
  path: '/store/products',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreOrdersRoute = StoreOrdersRouteImport.update({
  id: '/store/orders',
  path: '/store/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsExportRoute = ReportsExportRouteImport.update({
  id: '/reports/export',
  path: '/reports/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsActivityRoute = ReportsActivityRouteImport.update({
  id: '/reports/activity',
  path: '/reports/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const OrderFormIdRoute = OrderFormIdRouteImport.update({
  id: '/order/$formId',
  path: '/order/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSalesFormsRoute = MarketingSalesFormsRouteImport.update({
  id: '/marketing/sales-forms',
  path: '/marketing/sales-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryWaybillRoute = InventoryWaybillRouteImport.update({
  id: '/inventory/waybill',
  path: '/inventory/waybill',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryStockRecordRoute = InventoryStockRecordRouteImport.update({
  id: '/inventory/stock-record',
  path: '/inventory/stock-record',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductsRoute = InventoryProductsRouteImport.update({
  id: '/inventory/products',
  path: '/inventory/products',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryFaultyRoute = InventoryFaultyRouteImport.update({
  id: '/inventory/faulty',
  path: '/inventory/faulty',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryBuyStockRoute = InventoryBuyStockRouteImport.update({
  id: '/inventory/buy-stock',
  path: '/inventory/buy-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAgentStockRoute = InventoryAgentStockRouteImport.update({
  id: '/inventory/agent-stock',
  path: '/inventory/agent-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardRoute
  '/Settings': typeof SettingsRoute
  '/StoreManagement': typeof StoreManagementRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRoute
  '/chat': typeof ChatRoute
  '/customer-service': typeof CustomerServiceRoute
  '/finance': typeof FinanceRoute
  '/health': typeof HealthRoute
  '/integrations': typeof IntegrationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/productivity': typeof ProductivityRoute
  '/staff': typeof StaffRoute
  '/wallet': typeof WalletRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/f/$slug': typeof FSlugRoute
  '/inventory/agent-stock': typeof InventoryAgentStockRoute
  '/inventory/buy-stock': typeof InventoryBuyStockRoute
  '/inventory/faulty': typeof InventoryFaultyRoute
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/stock-record': typeof InventoryStockRecordRoute
  '/inventory/waybill': typeof InventoryWaybillRoute
  '/marketing/sales-forms': typeof MarketingSalesFormsRoute
  '/order/$formId': typeof OrderFormIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/reports/activity': typeof ReportsActivityRoute
  '/reports/export': typeof ReportsExportRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/products': typeof StoreProductsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardRoute
  '/Settings': typeof SettingsRoute
  '/StoreManagement': typeof StoreManagementRoute
  '/agents': typeof AgentsRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRoute
  '/chat': typeof ChatRoute
  '/customer-service': typeof CustomerServiceRoute
  '/finance': typeof FinanceRoute
  '/health': typeof HealthRoute
  '/integrations': typeof IntegrationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/productivity': typeof ProductivityRoute
  '/staff': typeof StaffRoute
  '/wallet': typeof WalletRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/f/$slug': typeof FSlugRoute
  '/inventory/agent-stock': typeof InventoryAgentStockRoute
  '/inventory/buy-stock': typeof InventoryBuyStockRoute
  '/inventory/faulty': typeof InventoryFaultyRoute
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/stock-record': typeof InventoryStockRecordRoute
  '/inventory/waybill': typeof InventoryWaybillRoute
  '/marketing/sales-forms': typeof MarketingSalesFormsRoute
  '/order/$formId': typeof OrderFormIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/reports/activity': typeof ReportsActivityRoute
  '/reports/export': typeof ReportsExportRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/products': typeof StoreProductsRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardRoute
  '/Settings': typeof SettingsRoute
  '/StoreManagement': typeof StoreManagementRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/businesses': typeof BusinessesRoute
  '/chat': typeof ChatRoute
  '/customer-service': typeof CustomerServiceRoute
  '/finance': typeof FinanceRoute
  '/health': typeof HealthRoute
  '/integrations': typeof IntegrationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/productivity': typeof ProductivityRoute
  '/staff': typeof StaffRoute
  '/wallet': typeof WalletRoute
  '/webhooks': typeof WebhooksRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/f/$slug': typeof FSlugRoute
  '/inventory/agent-stock': typeof InventoryAgentStockRoute
  '/inventory/buy-stock': typeof InventoryBuyStockRoute
  '/inventory/faulty': typeof InventoryFaultyRoute
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/stock-record': typeof InventoryStockRecordRoute
  '/inventory/waybill': typeof InventoryWaybillRoute
  '/marketing/sales-forms': typeof MarketingSalesFormsRoute
  '/order/$formId': typeof OrderFormIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/reports/activity': typeof ReportsActivityRoute
  '/reports/export': typeof ReportsExportRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/products': typeof StoreProductsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Dashboard'
    | '/Settings'
    | '/StoreManagement'
    | '/admin'
    | '/agents'
    | '/attendance'
    | '/auth'
    | '/businesses'
    | '/chat'
    | '/customer-service'
    | '/finance'
    | '/health'
    | '/integrations'
    | '/orders'
    | '/pricing'
    | '/productivity'
    | '/staff'
    | '/wallet'
    | '/webhooks'
    | '/admin/audit'
    | '/admin/broadcasts'
    | '/admin/flags'
    | '/admin/subscriptions'
    | '/admin/tenants'
    | '/customers/$id'
    | '/f/$slug'
    | '/inventory/agent-stock'
    | '/inventory/buy-stock'
    | '/inventory/faulty'
    | '/inventory/products'
    | '/inventory/stock-record'
    | '/inventory/waybill'
    | '/marketing/sales-forms'
    | '/order/$formId'
    | '/orders/$id'
    | '/reports/activity'
    | '/reports/export'
    | '/store/orders'
    | '/store/products'
    | '/admin/'
    | '/api/public/paystack-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Dashboard'
    | '/Settings'
    | '/StoreManagement'
    | '/agents'
    | '/attendance'
    | '/auth'
    | '/businesses'
    | '/chat'
    | '/customer-service'
    | '/finance'
    | '/health'
    | '/integrations'
    | '/orders'
    | '/pricing'
    | '/productivity'
    | '/staff'
    | '/wallet'
    | '/webhooks'
    | '/admin/audit'
    | '/admin/broadcasts'
    | '/admin/flags'
    | '/admin/subscriptions'
    | '/admin/tenants'
    | '/customers/$id'
    | '/f/$slug'
    | '/inventory/agent-stock'
    | '/inventory/buy-stock'
    | '/inventory/faulty'
    | '/inventory/products'
    | '/inventory/stock-record'
    | '/inventory/waybill'
    | '/marketing/sales-forms'
    | '/order/$formId'
    | '/orders/$id'
    | '/reports/activity'
    | '/reports/export'
    | '/store/orders'
    | '/store/products'
    | '/admin'
    | '/api/public/paystack-webhook'
  id:
    | '__root__'
    | '/'
    | '/Dashboard'
    | '/Settings'
    | '/StoreManagement'
    | '/admin'
    | '/agents'
    | '/attendance'
    | '/auth'
    | '/businesses'
    | '/chat'
    | '/customer-service'
    | '/finance'
    | '/health'
    | '/integrations'
    | '/orders'
    | '/pricing'
    | '/productivity'
    | '/staff'
    | '/wallet'
    | '/webhooks'
    | '/admin/audit'
    | '/admin/broadcasts'
    | '/admin/flags'
    | '/admin/subscriptions'
    | '/admin/tenants'
    | '/customers/$id'
    | '/f/$slug'
    | '/inventory/agent-stock'
    | '/inventory/buy-stock'
    | '/inventory/faulty'
    | '/inventory/products'
    | '/inventory/stock-record'
    | '/inventory/waybill'
    | '/marketing/sales-forms'
    | '/order/$formId'
    | '/orders/$id'
    | '/reports/activity'
    | '/reports/export'
    | '/store/orders'
    | '/store/products'
    | '/admin/'
    | '/api/public/paystack-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  StoreManagementRoute: typeof StoreManagementRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  BusinessesRoute: typeof BusinessesRoute
  ChatRoute: typeof ChatRoute
  CustomerServiceRoute: typeof CustomerServiceRoute
  FinanceRoute: typeof FinanceRoute
  HealthRoute: typeof HealthRoute
  IntegrationsRoute: typeof IntegrationsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProductivityRoute: typeof ProductivityRoute
  StaffRoute: typeof StaffRoute
  WalletRoute: typeof WalletRoute
  WebhooksRoute: typeof WebhooksRoute
  CustomersIdRoute: typeof CustomersIdRoute
  FSlugRoute: typeof FSlugRoute
  InventoryAgentStockRoute: typeof InventoryAgentStockRoute
  InventoryBuyStockRoute: typeof InventoryBuyStockRoute
  InventoryFaultyRoute: typeof InventoryFaultyRoute
  InventoryProductsRoute: typeof InventoryProductsRoute
  InventoryStockRecordRoute: typeof InventoryStockRecordRoute
  InventoryWaybillRoute: typeof InventoryWaybillRoute
  MarketingSalesFormsRoute: typeof MarketingSalesFormsRoute
  OrderFormIdRoute: typeof OrderFormIdRoute
  ReportsActivityRoute: typeof ReportsActivityRoute
  ReportsExportRoute: typeof ReportsExportRoute
  StoreOrdersRoute: typeof StoreOrdersRoute
  StoreProductsRoute: typeof StoreProductsRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productivity': {
      id: '/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof ProductivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-service': {
      id: '/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof CustomerServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/StoreManagement': {
      id: '/StoreManagement'
      path: '/StoreManagement'
      fullPath: '/StoreManagement'
      preLoaderRoute: typeof StoreManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Settings': {
      id: '/Settings'
      path: '/Settings'
      fullPath: '/Settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard': {
      id: '/Dashboard'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/store/products': {
      id: '/store/products'
      path: '/store/products'
      fullPath: '/store/products'
      preLoaderRoute: typeof StoreProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/orders': {
      id: '/store/orders'
      path: '/store/orders'
      fullPath: '/store/orders'
      preLoaderRoute: typeof StoreOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/export': {
      id: '/reports/export'
      path: '/reports/export'
      fullPath: '/reports/export'
      preLoaderRoute: typeof ReportsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/activity': {
      id: '/reports/activity'
      path: '/reports/activity'
      fullPath: '/reports/activity'
      preLoaderRoute: typeof ReportsActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/order/$formId': {
      id: '/order/$formId'
      path: '/order/$formId'
      fullPath: '/order/$formId'
      preLoaderRoute: typeof OrderFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/sales-forms': {
      id: '/marketing/sales-forms'
      path: '/marketing/sales-forms'
      fullPath: '/marketing/sales-forms'
      preLoaderRoute: typeof MarketingSalesFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/waybill': {
      id: '/inventory/waybill'
      path: '/inventory/waybill'
      fullPath: '/inventory/waybill'
      preLoaderRoute: typeof InventoryWaybillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/stock-record': {
      id: '/inventory/stock-record'
      path: '/inventory/stock-record'
      fullPath: '/inventory/stock-record'
      preLoaderRoute: typeof InventoryStockRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/products': {
      id: '/inventory/products'
      path: '/inventory/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof InventoryProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/faulty': {
      id: '/inventory/faulty'
      path: '/inventory/faulty'
      fullPath: '/inventory/faulty'
      preLoaderRoute: typeof InventoryFaultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/buy-stock': {
      id: '/inventory/buy-stock'
      path: '/inventory/buy-stock'
      fullPath: '/inventory/buy-stock'
      preLoaderRoute: typeof InventoryBuyStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/agent-stock': {
      id: '/inventory/agent-stock'
      path: '/inventory/agent-stock'
      fullPath: '/inventory/agent-stock'
      preLoaderRoute: typeof InventoryAgentStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  StoreManagementRoute: StoreManagementRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRoute,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  BusinessesRoute: BusinessesRoute,
  ChatRoute: ChatRoute,
  CustomerServiceRoute: CustomerServiceRoute,
  FinanceRoute: FinanceRoute,
  HealthRoute: HealthRoute,
  IntegrationsRoute: IntegrationsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PricingRoute: PricingRoute,
  ProductivityRoute: ProductivityRoute,
  StaffRoute: StaffRoute,
  WalletRoute: WalletRoute,
  WebhooksRoute: WebhooksRoute,
  CustomersIdRoute: CustomersIdRoute,
  FSlugRoute: FSlugRoute,
  InventoryAgentStockRoute: InventoryAgentStockRoute,
  InventoryBuyStockRoute: InventoryBuyStockRoute,
  InventoryFaultyRoute: InventoryFaultyRoute,
  InventoryProductsRoute: InventoryProductsRoute,
  InventoryStockRecordRoute: InventoryStockRecordRoute,
  InventoryWaybillRoute: InventoryWaybillRoute,
  MarketingSalesFormsRoute: MarketingSalesFormsRoute,
  OrderFormIdRoute: OrderFormIdRoute,
  ReportsActivityRoute: ReportsActivityRoute,
  ReportsExportRoute: ReportsExportRoute,
  StoreOrdersRoute: StoreOrdersRoute,
  StoreProductsRoute: StoreProductsRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
